import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "./providers";
import "@/Styles/globals.css";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body> */}
      <body className={inter.className + " w-screen max-w-full overflow-x-hidden "}>
      <div className="relative overflow-x-hidden">
          <div className="main">
              <div className="gradient" />
          </div>
          <div className="app scroll-smooth">
            <Providers>
              {children}
              <Toaster richColors position='top-center' />
            </Providers>
          </div>
      </div>
      </body>
    </html>
  )
}
